version: '3'

services:

  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: radwellscraper
    volumes:
      - mongo-data:/data/db
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.11-alpine
    ports:
      - "5672:5672"
    volumes:
      - mq-data:/var/lib/rabbitmq/

volumes:
  mongo-data:
  mq-data: